# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5babfd12bf628e813ea8fba89771c56d152c3f32d03993b58982d9bbb7d8ce2e298721c919ff7879a19626ee29b3fc240bb5a30cf447a4fba5d68dad997afa7

test:
  secret_key_base: 3493dacbcba16cb5fe86f2d4a8540a304a1c7ba61f21cf3baee5a3593dd5032f8a14fe7953806146aa3176b9b01318e8f76565ee7aefcf9066f9a5049af2472c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
